name: Build and Deploy (example)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby (for puppet-lint)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - name: Install puppet-lint
        run: gem install puppet-lint
      - name: Run puppet-lint
        run: puppet-lint infra/puppet/ || true

  terraform-plan:
    name: Terraform Init & Plan
    runs-on: ubuntu-latest
    needs: lint
    env:
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: |
          cd infra/terraform
          terraform init
      - name: Terraform Plan
        run: |
          cd infra/terraform
          terraform plan -out=tfplan
      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/terraform/tfplan

  terraform-apply:
    name: Terraform Apply (manual)
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/terraform
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd infra/terraform
          terraform apply -auto-approve tfplan
